version: '3'
services:
  go:
    image: golang:1.17.6-bullseye
    environment:
      - http_proxy
      - https_proxy
    volumes:
      - .:/workspace
    working_dir: /workspace
    command:
      - /bin/bash
