version: '3'
services:
  go:
    image: golang:1.17.6-bullseye
    environment:
      - http_proxy
      - https_proxy
    volumes:
      - .:/workspace
    working_dir: /workspace
    entrypoint: go
  aws:
    image: amazon/aws-cli:2.4.15
    environment:
      - http_proxy
      - https_proxy
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - AWS_SESSION_TOKEN
    volumes:
      - .:/workspace
    working_dir: /workspace
  jenkins:
    image: jenkins/jenkins:2.319.2-lts-alpine
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home
      - .:/workspace
volumes:
  jenkins_home: {}
